name: gfin_app
description: Flutter app for financial management
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  fl_chart: ^0.63.0

flutter:
  uses-material-design: true
